name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  # You can use a specific Ubuntu version
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust Node.js version if necessary

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Or your specific test command

